### PR TITLE
Allow other implementations of `document`

### PR DESCRIPTION
**Pull request by tomekwi**
The check only makes sense in a browser environment anyway.

### CODE REVIEW

**Comment by tomekwi** [comment]
Hi, is there anything I can do to help this move forward? I’m using this lib to test a project in node. I see that [you already allow passing a custom `document` object](https://github.com/component/domify/blob/d798cce38eed64aeef208ef72fbef7d00e5ecbf9/index.js#L66).

However, with [`a1e20cc`](https://github.com/component/domify/commit/a1e20cc) you introduced a check which only works in a browser. [This line](https://github.com/component/domify/commit/a1e20cc60447b58627bb154d824fbcf9cec2c214#diff-168726dbe96b3ce427e7fedce31bb0bcR12) results in a ReferenceError.

I’ve also made another PR (#40) to document the usage of <code>parse(html, <b>doc</b>)</code>.

**Comment by tomekwi** [comment]
Hi, thanks for merging #40!

I’ll just ping you that *domify* doesn’t really work in node until this PR is merged. @a1e20cc broke node support with a little crunchy bug.

**Comment by stephenmathieson** [comment]
ah, ok.

**Comment by tomekwi** [comment]
:+1:

**Comment by tomekwi** [comment]
@stephenmathieson release please? I need the change from @b6bef0f in https://github.com/tomekwi/virtual-dom-lite

**Comment by stephenmathieson** [comment]
`1.4.0` ;)

**Comment by tomekwi** [comment]
Thanks! :wine:

**Pull request merged**
